### PR TITLE
tianchi: add props for sensors

### PR DESCRIPTION
**Pull request by stellirin**
Resolves some logspam on boot

### CODE REVIEW

**Comment by jerpelea** [comment]
Please keep the props in mk

**Comment by AdFad666** [comment]
I think it's better to add all of our own properties to a system.prop not to the aosp_aXXXX.mk. When they are added with PRODUCT_PROPERTY_OVERRIDES they get merged into the dalvik section at the end, without any comments we may want to add. Additions via (multiple) system.prop files are added together in one place.

It's quite trivial, but it could help us or anyone else who wants to analyse a build in the future, as all our additions are in the central part of the final build.prop.

**Comment by jerpelea** [comment]
i know but we want to keep same layout on all devices 
please keep mk unchanged

**Comment by jerpelea** [comment]
please update PR

**Pull request closed without merging**
